import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'

const STATES = [
  { key: 'alabama', name: 'Alabama' },
  { key: 'alaska', name: 'Alaska' },
  { key: 'arizona', name: 'Arizona' },
  { key: 'arkansas', name: 'Arkansas' },
  { key: 'california', name: 'California' },
  { key: 'colorado', name: 'Colorado' },
  { key: 'connecticut', name: 'Connecticut' },
  { key: 'delaware', name: 'Delaware' },
  { key: 'flordia', name: 'Flordia' },
  { key: 'georgia', name: 'Georgia' },
  { key: 'hawaii', name: 'Hawaii' },
  { key: 'idaho', name: 'Idaho' },
  { key: 'illinois', name: 'Illinois' },
  { key: 'indiana', name: 'Indiana' },
  { key: 'iowa', name: 'Iowa' },
  { key: 'kansas', name: 'Kansas' },
  { key: 'kentucky', name: 'Kentucky' },
  { key: 'louisiana', name: 'Louisiana' },
  { key: 'maine', name: 'Maine' },
  { key: 'maryland', name: 'Maryland' },
  { key: 'massachusetts', name: 'Massachusetts' },
  { key: 'michigan', name: 'Michigan' },
  { key: 'minnesota', name: 'Minnesota' },
  { key: 'mississippi', name: 'Mississippi' },
  { key: 'missouri', name: 'Missouri' },
  { key: 'montana', name: 'Montana' },
  { key: 'nebraska', name: 'Nebraska' },
  { key: 'nevada', name: 'Nevada' },
  { key: 'new-hampshire', name: 'New Hampshire' },
  { key: 'new-jersey', name: 'New Jersey' },
  { key: 'new-mexico', name: 'New Mexico' },
  { key: 'new-york', name: 'New York' },
  { key: 'north-carolina', name: 'North Carolina' },
  { key: 'north-dakota', name: 'North Dakota' },
  { key: 'ohio', name: 'Ohio' },
  { key: 'oklahoma', name: 'Oklahoma' },
  { key: 'oregon', name: 'Oregon' },
  { key: 'pennslyvania', name: 'Pennslyvania' },
  { key: 'rhode-island', name: 'Rhode Island' },
  { key: 'south-carolina', name: 'South Carolina' },
  { key: 'south-dakota', name: 'South Dakota' },
  { key: 'tennessee', name: 'Tennessee' },
  { key: 'texas', name: 'Texas' },
  { key: 'utah', name: 'Utah' },
  { key: 'vermont', name: 'Vermont' },
  { key: 'virginia', name: 'Virginia' },
  { key: 'washington', name: 'Washington' },
  { key: 'west-virginia', name: 'West Virginia' },
  { key: 'wisconsin', name: 'Wisconsin' },
  { key: 'wyoming', name: 'Wyoming' },
]

export default function Home() {
  const [color, setColor] = useState('red')
  const [usState, setUsState] = useState(rand_state())
  console.log(`color = ${color}`)
  console.log(`state = ${usState.key} ${usState.name}`)

  function rand_state() {
    const i = Math.floor(Math.random() * STATES.length)
    return STATES[i]
  }

  async function onColorSubmit() {
    console.log('submit!')
    setUsState(rand_state())
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Choose a color for this U.S. state
        </h1>

        <p className={styles.description}>
          <select onChange={(e) => { setColor(e.target.value) }}>
            <option value='red'>Red</option>
            <option value='orange'>Orange</option>
            <option value='green'>Green</option>
            <option value='blue'>Blue</option>
            <option value='purple'>Purple</option>
            <option value='violet'>Violet</option>
          </select>
          <button onClick={onColorSubmit}>Submit</button>
        </p>

        <h2>{usState.name}</h2>
        <div className={styles.grid}>
          <img src={`/${usState.key}-outline.jpg`}></img>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


